Repository Esmorga-Backend/esmorga-backend, pull requests merged in 2024-07, with the labels that each got.

#52 [MOB-78] 🐛 BE - POST Events API - No 'some inputs are missing' error shown
  src/infrastructure/http/dtos/create-event.dto.ts
  test/jest-unit/infrastructure/http/dtos/create-event.dto.spec.ts
Labels: bug 🐛

#48 [MOB-41] - POST Register endpoint
  package-lock.json
  package.json
  src/app.module.ts
  src/application/handler/account/index.ts
  src/application/handler/account/login.service.ts
  src/application/handler/account/refresh-token.service.ts
  src/application/handler/account/register.service.ts
  src/application/handler/event/create-event.service.ts
  src/application/handler/event/get-event-list.service.ts
  src/config/execute-migrations.ts
  src/config/index.ts
  src/config/logger.ts
  src/domain/errors/email-conflict-error.ts
  src/domain/errors/index.ts
  src/domain/services/encode-value.ts
  src/domain/services/index.ts
  src/infrastructure/db/errors/conflict-error.ts
  src/infrastructure/db/errors/index.ts
  src/infrastructure/db/repositories/account.repository.ts
  src/infrastructure/db/repositories/event.repository.ts
  src/infrastructure/db/repositories/tokens.repository.ts
  src/infrastructure/db/schema/user.schema.ts
  src/infrastructure/http/controllers/account.controller.ts
  src/infrastructure/http/controllers/event.controller.ts
  src/infrastructure/http/dtos/account-register.dto.ts
  src/infrastructure/http/dtos/index.ts
  src/infrastructure/http/middlewares/index.ts
  src/infrastructure/http/middlewares/request-id.middleware.ts
  src/infrastructure/http/modules/account.module.ts
  src/infrastructure/http/req-decorators/index.ts
  src/infrastructure/http/req-decorators/x-request-id.ts
  src/infrastructure/http/swagger/decorators/account.ts
  src/infrastructure/http/swagger/decorators/events.ts
  src/infrastructure/http/swagger/headers/account-headers.ts
  src/infrastructure/http/swagger/headers/create-event-headers.ts
  src/infrastructure/http/swagger/headers/event-headers.ts
  src/infrastructure/http/swagger/headers/index.ts
  src/infrastructure/http/swagger/headers/refresh-token-headers.ts
  src/infrastructure/http/swagger/responses/account-responses.ts
  src/infrastructure/http/swagger/responses/event-responses.ts
  src/main.ts
  test/jest-component/account/register.spec.ts
  test/jest-component/jest-component.config.json
  test/jest-unit/infrastructure/http/dtos/account-register.dto.spec.ts
  test/mocks/common-data.ts
  test/mocks/dtos/account-register.ts
  test/mocks/dtos/account.ts
  test/mocks/dtos/index.ts
  test/mocks/dtos/user-profile.ts
  test/mocks/test.env.ts
Labels: feature 🤓

#55 [MOB-81] POST Register API - Incomplete error message for password validation
  .github/pull_request_template.md
  src/infrastructure/http/dtos/account-register.dto.ts
Labels: bug 🐛

#57 [MOB-83] POST Login API - Email not case insensitive
  src/application/handler/account/login.service.ts
  src/infrastructure/http/dtos/account-login.dto.ts
Labels: bug 🐛

#59 [MOB-85] POST Events API - Create new event with more than maximum allowed characters on imageUrl
  src/infrastructure/http/dtos/create-event.dto.ts
  src/infrastructure/http/errors/exception-filter.ts
  test/jest-unit/infrastructure/http/dtos/create-event.dto.spec.ts
Labels: bug 🐛

#56 [MOB-62] POST Events API - Improve validation in case invalid information
  src/infrastructure/http/dtos/create-event.dto.ts
  test/jest-unit/infrastructure/http/dtos/create-event.dto.spec.ts
Labels: feature 🤓

#58 [MOB-84] POST Register API - Special characters not treated as special characters
  src/infrastructure/http/dtos/account-register.dto.ts
Labels: bug 🐛

#60 [MOB-112] Changing error message in createEventDto description
  src/infrastructure/http/dtos/create-event.dto.ts
  test/jest-unit/infrastructure/http/dtos/create-event.dto.spec.ts
Labels: bug 🐛

#54 [MOB-75] Change password hash strategy
  migrations/1719909591756_change_password_with_argon2.js
  migrations/1719909591756_change_password_with_argon2.ts
  package-lock.json
  package.json
  src/application/handler/account/login.service.ts
  src/application/handler/account/register.service.ts
  src/domain/errors/api-error.ts
  src/domain/services/encode-value.ts
  src/domain/services/validate-login-credentials.ts
  src/infrastructure/db/repositories/tokens.repository.ts
  test/jest-component/account/login.spec.ts
  test/jest-component/account/register.spec.ts
  test/jest-unit/domain/services/validate-login-credentials.spec.ts
  test/mocks/db/user.ts
Labels: feature 🤓, risky 💀

#62 [MOB-115] Register API - The error message does not help to understand the problem
  src/infrastructure/http/dtos/account-register.dto.ts
Labels: bug 🐛

#65 [MOB-117] Change password hash strategy - 500 when login
  src/domain/services/validate-login-credentials.ts
Labels: bug 🐛

#61 [MOB-36] Update existing Jest integration tests to adapt to Gherkin notation
  .gitignore
  README.md
  package-lock.json
  package.json
  test/cypress-e2e/cypress.config.js
  test/cypress-e2e/cypress/e2e/features/MOB_Feature/steps.cy.js
  test/cypress-e2e/cypress/e2e/pages/account/api_login.js
  test/cypress-e2e/cypress/e2e/pages/account/api_refresh_token.js
  test/cypress-e2e/cypress/e2e/pages/api_basic.js
  test/cypress-e2e/cypress/e2e/pages/api_events.js
  test/cypress-e2e/cypress/e2e/pages/events/api_events.js
  test/jest-component/features/steps/account/login-steps.ts
  test/jest-component/features/steps/account/refresh-token-steps.ts
  test/jest-component/features/steps/account/register-step.ts
  test/jest-component/features/steps/events/get-events-steps.ts
  test/jest-component/features/steps/events/post-events-steps.ts
  test/jest-component/features/steps/jest-cucumber-setup.ts
  test/jest-component/features/steps/reusable-steps.ts
  test/jest-component/instruments/gen-random.ts
  test/jest-component/instruments/swagger-things.ts
  test/jest-component/jest-cucumber-setup.ts
  test/jest-component/steps-config.ts
Labels: feature 🤓

#64 [MOB-51] BE - Cucumber and others, logs and outputs when run pipe SetupComment with Coverage
  .github/actions/DeployToQA/action.yaml
  .github/actions/SlackCom/action.yaml
  .github/actions/runComponentTests/action.yaml
  .github/actions/runE2ETests/action.yaml
  .github/actions/runPostmanTests/action.yaml
  .github/actions/runReporting/action.yaml
  .github/actions/runUnitTests/action.yaml
  .github/workflows/WhenMainChanges.yml
  .github/workflows/WhenPR.yml
  .gitignore
  package-lock.json
  package.json
  test/cypress-e2e/cypress.config.js
  test/jest-component/jest-component.config.json
  test/jest-unit/jest-unit.config.json
  test/scripts/features-tool.js
  test/scripts/lib/Aio.js
  test/scripts/lib/GitHelper.js
Labels: feature 🤓
